### PR TITLE
Upgrade Swiper to version 5

### PR DESCRIPTION
**Pull request by alejandroiglesias**
This change also moves the swiper dependency to `peerDependencies` in `package.json`, which means that it allows the users to use specific versions but also requires the user to manually add swiper alongside vue-awesome-swiper.

```
npm install swiper vue-awesome-swiper
```

### CODE REVIEW

**Comment by vinialbano** [comment]
Upgrading to Swiper 5 would be awesome! The current version is too outdated...

**Comment by wiemann** [comment]
+1

**Comment by wiemann** [comment]
@alejandroiglesias This breaks Pagnation and next/prev Buttons

**Comment by 7iomka** [comment]
> @alejandroiglesias This breaks Pagnation and next/prev Buttons

any workaround?

**Pull request merged**
