### PR TITLE
keep component alive during page transition

### PR DESCRIPTION
**Pull request by guins**
Hello, I added a `cleanStylesOnDestroy` props, so we can prevent the component from cleaning Swiper styles during the `beforeDestroy` lifecycle event. Indeed the `beforeDestroy` event is emitted right away when a component should be removed, even if the component (or one of its parents) have a transition out animation. So this allows you to keep the component alive, and properly styled, during a page transition.

### CODE REVIEW

**Comment by hoektoe** [comment]
@guins is the owner of this repo still alive? He hasn't done any commits in past 3 months

**Comment by hoektoe** [comment]
@surmon-china can we get some love for this project and pull-request

**Comment by maximelebreton** [comment]
Thanks for the fix!

To get working, don't forget to set `:cleanStylesOnDestroy` prop to `false`
```vue
<swiper :cleanStylesOnDestroy="false" ref="mySwiper"></swiper>
```

**Comment by surmon-china** [comment]
Thanks!

v4.0.0 new feature:

`<swiper :options="options" :auto-destroy="false">`

**Comment by surmon-china** [comment]
Merged!  [here](https://github.com/surmon-china/vue-awesome-swiper#swiper-component-api),  enjoy it!

**Comment by hoektoe** [comment]
Thank you busy updating our packages at the moment. appreciated this @surmon-china

**Pull request closed without merging**
