### PR TITLE
Fix component ssr

### PR DESCRIPTION
**Pull request by shrpne**
With this fix, I can use component approach with ssr, no need for directive approach.
Before this fix even dist/ssr.js failed to me because of window.

I had not realized why there is `window.swiper`, so I just guarded window usage with simple `typeof window` check, but looks like it should work even if we remove `window.Swiper` entirely and just make `const Swiper = _Swiper` ?

Tests failed because of prettier 1.13.0, which is dependency of vue-loader, I can add prettier 1.12.0 to package.json if u want, so test will work

Last test "Multi edirot directive instance" is failing, but it was failing before my change too

### CODE REVIEW

**Comment by wychootf4** [comment]
https://github.com/NightCatSama/vue-slider-component/issues/114#issuecomment-353827607
checkout this dfeinberg5 did the real magic, it saved my day after I had tried everything.

**Comment by antony** [comment]
Would be great to get this merged. The current SSR situation is that the plugin doesn't support SSR (it just turns it off)

**Comment by gianniskarmas** [comment]
Why isn't this getting merged?
Could you please?

**Comment by ericmuyser** [comment]
Mergeeeeeeeeeeeeeeeee

**Comment by gepifanio** [comment]
Running into the same issue, decided to change the library.

**Comment by antony** [comment]
Looks like this project needs a new maintainer. I've since switched to Svelte + Sapper instead of Vue + Nuxt, but I use [https://glidejs.com/](https://glidejs.com/) which should be fairly easy to integrate into a Nuxt app too. Give it a go if you're stuck.

**Comment by tiwitico** [comment]
Still no update?

**Comment by Seonghui** [comment]
I had the same problem, but solved with mode: 'client' option. Nothing changed with example code for ssr but just add it code below.
```
plugins: [{ src: '~/plugins/swiper', mode: 'client' }],
```

then everything works fine.
Check it the official document. https://nuxtjs.org/guide/plugins

**Comment by antony** [comment]
@Seonghui yes - making the component client only always works, but this is different to creating an SSR compatible component.

**Comment by Oleg-Arkhipov** [comment]
@antony I was able to fix SSR issue without changes to the library (although this MR works perfect):

```
new webpack.ProvidePlugin({
    'window.Swiper': 'swiper/dist/js/swiper.js',
}),
```

But I am not 100% sure how that plays together with bundle splitting and effective bundle size minimizing. I guess it just adds the swiper everywhere.

**Comment by gianniskarmas** [comment]
@Oleg-Arkhipov how exactly did you implement this without changing package files?
I added the below in nuxt config but when I enable ssr in plugin I still get window is not defined:
```
import webpack from 'webpack'
module.exports = {
    build: {
        plugins: [
            new webpack.ProvidePlugin({
                'window.Swiper': 'swiper/dist/js/swiper.js'
```

**Comment by antony** [comment]
@gianniskarmas yeah I think that's equivalent to just including the script tag in your `<head>`.

**Comment by Oleg-Arkhipov** [comment]
@gianniskarmas I added only ProvidePlugin, nothing more. It makes `window.Swiper` defined and accessible. But I do not use Nuxt, so your problem probably has something to do with it.

**Comment by Oleg-Arkhipov** [comment]
@antony if that becomes a problem anyone willing to use this library can create a fork with this MR merged and use it in their projects until @surmon-china fixes it.

**Comment by antony** [comment]
If you don't use SSR none of this is a problem anyway. I would suggest that anybody wanting a more permanent fix forks and maintains this library as it appears to be abandoned.

**Comment by Oleg-Arkhipov** [comment]
@antony I use SSR and love my images to be in `` tags in initial response, instead of emptiness. Too bad @surmon-china abandoned merging that when his library otherwise works really well, just small  fix required.

**Pull request merged**
